version: "3.7"
services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.1
    ports:
      - "9090:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev